FROM nginx:1.15.11-alpine

ADD local.conf /etc/nginx/conf.d/default.conf
ADD cors.conf /etc/nginx/cors.conf
ADD cache-inner.conf /etc/nginx/cache-inner.conf
ADD cache-outer.conf /etc/nginx/cache-outer.conf

